### ISSUE TITLE
Warnings in MacOS

### ISSUE THREAD

**Issue by danigargu** [Jinmo/ifred#8]
Hi,

A very useful plugin!
When i start IDA in MacOS, I receive the following "warnings":

```
dlopen(/Applications/IDA Pro 7.2/ida64.app/Contents/MacOS/plugins/ida_palette64.dylib): dlopen(/Applications/IDA Pro 7.2/ida64.app/Contents/MacOS/plugins/ida_palette64.dylib, 2): Symbol not found: _PyBaseObject_Type
  Referenced from: /Applications/IDA Pro 7.2/ida64.app/Contents/MacOS/plugins/ida_palette64.dylib
  Expected in: flat namespace
 in /Applications/IDA Pro 7.2/ida64.app/Contents/MacOS/plugins/ida_palette64.dylib
/Applications/IDA Pro 7.2/ida64.app/Contents/MacOS/plugins/ida_palette64.dylib: can't load file
```
But then the plugin works correctly.
Thanks!

**Comment by Jinmo** [comment]
Hello, thanks for using the plugin! :+1:

Just investigated the issue and found that it was because of the loading order:
ifred is loaded before IDAPython and relies on run-time linking (`<self>`) like [pybind11 does](https://github.com/pybind/pybind11/blob/06d021b6e46905ffb84c3646b35739f9c5e70aad/tools/pybind11Tools.cmake#L165)...

![image](https://user-images.githubusercontent.com/285364/57473540-02a7f500-72cb-11e9-9b29-a68c22b40be6.png)

Fortunately, IDA Pro scans and loads the plugins once again, but the warning still exists...

Maybe a separated python plugin (`plugins/*.py`) that loads `ida_palette64.dylib` and skips can be made (locally worked). I'll be likely choosing this way.

Or, statically linking ifred with libpython2.7.dylib, I must find out how IDAPython is linked. `otool -L` says that it uses `/System/Library/Frameworks/Python.framework/Versions/2.7/Python` in my mac, but I'm still not sure if it applies to all of IDA >=7.0 versions.

**Comment by Jinmo** [comment]
This is fixed in bf63c2 by linking the plugin with IDAPython plugin.
Huge thanks for the report!
